server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yshcoffee/spring-cloud-repo.git
          
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/